// Package main
package main

import (
	"log"

	"github.com/agustiawanilham/go-api-karyawan/db"
	"github.com/agustiawanilham/go-api-karyawan/routes"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cache"
	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/gofiber/fiber/v2/middleware/logger"
	"github.com/gofiber/fiber/v2/middleware/recover"
	"github.com/gofiber/swagger"

	// swagger handler
	// docs are generated by Swag CLI, you have to import them.
	// replace with your own docs folder, usually "github.com/username/reponame/docs"
	_ "github.com/agustiawanilham/go-api-karyawan/docs"
)

// @title Karyawan API
// @version 1.0
// @description Simple CRUD API Karyawan
// @host      localhost:8080
// @BasePath  /api/v1
func main() {
	app := fiber.New()

	app.Use(cors.New(cors.Config{
		AllowHeaders:     "Origin,Content-Type,Accept,Content-Length,Accept-Language,Accept-Encoding,Connection,Access-Control-Allow-Origin,X-CSRF-Token",
		AllowCredentials: true,
		AllowMethods:     "GET,POST,DELETE,PATCH,OPTIONS",
	}))

	app.Use(recover.New())
	app.Use(cache.New())

	app.Use(logger.New())
	db.ConnectDatabase()

	// Setup swagger
	route := app.Group("/swagger")
	route.Get("*", swagger.HandlerDefault)

	routes.SetupRoutes(app)

	if err := app.Listen(":3000"); err != nil {
		log.Fatal(err)
	}
}
